# Step 1: Calibration of camera intrinsic values

In [1]:
import numpy as np
import cv2
import glob

## Chessboard calibration

In [2]:
CAMERA_ID = 'david'
CHESSBOARD_SQUARE_LENGTH_MM = 20
CHESSBOARD_DIMENSIONS = (9,6)

In [3]:
# termination criteria
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((CHESSBOARD_DIMENSIONS[0] * CHESSBOARD_DIMENSIONS[1],3), np.float32)

# TODO: check if this is the correct way to adjust the sizes. Used this accordint to: https://stackoverflow.com/questions/37310210/camera-calibration-with-opencv-how-to-adjust-chessboard-square-size
objp[:,:2] = np.mgrid[0:CHESSBOARD_DIMENSIONS[0],0:CHESSBOARD_DIMENSIONS[1]].T.reshape(-1,2) * CHESSBOARD_SQUARE_LENGTH_MM

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

images = glob.glob(f'data/calibration/{CAMERA_ID}/*.png')
print(f'Found {len(images)} calibration images')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv2.findChessboardCorners(gray, CHESSBOARD_DIMENSIONS, None)

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)

        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        imgpoints.append(corners2)
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (CHESSBOARD_DIMENSIONS[0],CHESSBOARD_DIMENSIONS[1]), corners2,ret)
    else:
        print(f'Could not find chessboard corners in image {fname}')


Found 19 calibration images
Could not find chessboard corners in image data/calibration/david/calibration_frame_2021-04-02 16:39:56.783532.png
Could not find chessboard corners in image data/calibration/david/calibration_frame_2021-04-02 16:39:36.784381.png
Could not find chessboard corners in image data/calibration/david/calibration_frame_2021-04-02 16:38:46.784388.png
Could not find chessboard corners in image data/calibration/david/calibration_frame_2021-04-02 16:39:41.783697.png


In [4]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)
print('Image Dimensions')
print(gray.shape)
print('Intrinsic Matrix')
print(mtx)
print('Distortion Coefficients')
print(dist)
print('Rotation Vectors')
print(rvecs)
print('Translation Vectors')
print(tvecs)

Image Dimensions
(480, 640)
Intrinsic Matrix
[[563.75694808   0.         332.16377885]
 [  0.         558.41973861 215.14146953]
 [  0.           0.           1.        ]]
Distortion Coefficients
[[ 0.22044414 -0.71477837 -0.00554924 -0.00207883  0.98609804]]
Rotation Vectors
[array([[-0.01860486],
       [ 0.17610102],
       [-0.07497551]]), array([[0.11681047],
       [0.15346942],
       [1.69163244]]), array([[0.20858081],
       [0.09252583],
       [2.32986873]]), array([[0.166542  ],
       [0.12575134],
       [1.95168276]]), array([[0.24231219],
       [0.06742631],
       [2.60452293]]), array([[0.17773233],
       [0.09973117],
       [2.4501321 ]]), array([[0.29928722],
       [0.0226388 ],
       [3.11977239]]), array([[-0.32006937],
       [-0.03510258],
       [-3.10804777]]), array([[-0.11721898],
       [ 0.12362866],
       [-1.17105577]]), array([[-0.48183015],
       [-0.13182307],
       [-2.98426722]]), array([[-0.27082947],
       [-0.02717017],
       [-3.12071